[package]
name = "electrs"
version = "0.8.8"
authors = ["Roman Zeyde <me@romanzey.de>"]
description = "An efficient re-implementation of Electrum Server in Rust"
license = "MIT"
homepage = "https://github.com/romanz/electrs"
repository = "https://github.com/romanz/electrs"
keywords = ["bitcoin", "electrum", "server", "index", "database"]
documentation = "https://docs.rs/electrs/"
readme = "README.md"
edition = "2018"
build = "build.rs"

[package.metadata.configure_me]
spec = "internal/config_specification.toml"

[profile.release]
lto = true

[features]
default = ["rocksdb/snappy", "rocksdb/lz4", "rocksdb/zstd", "rocksdb/zlib", "rocksdb/bzip2"]

[dependencies]
base64 = "0.10"
bincode = "1.0"
bitcoin = { version = "0.26.0", features = ["use-serde"] }
cbor = "0.4.1"
configure_me = "0.4.0"
crossbeam-channel = "0.3"
dirs-next = "2.0.0"
error-chain = "0.12"
glob = "0.3"
hex = "0.3"
libc = "0.2"
log = "0.4"
lru = "0.6.1"
num_cpus = "1.0"
maplit = "1.0.2"
page_size = "0.4"
prometheus = "0.10"
protobuf = "= 2.14.0"   # https://github.com/stepancheg/rust-protobuf/blob/master/CHANGELOG.md#2150---2020-06-21
rocksdb = { version = "0.12.2", default-features = false } # due to https://github.com/romanz/electrs/issues/193
rustc-serialize = "0.3"
serde = "1.0"
serde_cbor = "0.11.1"
serde_derive = "1.0"
serde_json = "1.0"
sha2 = "0.9.2"
signal-hook = "0.1"
stderrlog = "0.5.1"
sysconf = ">=0.3.4"
time = "0.1"
tiny_http = "0.6"

[build-dependencies]
configure_me_codegen = "0.4.0"
